### ISSUE TITLE
Version 1.1.1 is incompatible with Cacheman

### ISSUE THREAD

**Issue by mdurling** [cayasso/cacheman-redis#10]
require('cacheman-redis') returns the following:

{ default: [Function: RedisStore] }

making it incompatible with cacheman which is expecting a function.

I can use cacheman-redis directly by using:

require('cacheman-redis').default, but this is not what cacheman does or expects

**Comment by mdurling** [comment]
In version 1.0.1, require('cacheman-redis') returns [Function: RedisStore]

**Comment by cayasso** [comment]
Can I see your Cacheman initialization code?

**Comment by mdurling** [comment]
I have simplified it to:

let Cacheman = require('cacheman');
let Cache = new Cacheman('test', {engine: 'redis'});

It generated the following exception:

node --debug-brk=35754 --nolazy server.js 
Debugger listening on port 35754
/Users/mdurling/Repos/auth-api/node_modules/cacheman/node/index.js:111
        this._engine = new Engine(options || this.options, this);
                       ^
TypeError: Engine is not a function
    at Cacheman.engine (/Users/mdurling/Repos/auth-api/node_modules/cacheman/node/index.js:111:24)
    at new Cacheman (/Users/mdurling/Repos/auth-api/node_modules/cacheman/node/index.js:68:10)
    at Object.<anonymous> (/Users/mdurling/Repos/auth-api/services/cache.js:4:13)
    at Module._compile (module.js:435:26)

**Comment by cayasso** [comment]
Ok I see what you mean, this might be a babel issue

**Comment by mdurling** [comment]
That's what we were surmising here; something with babel/build.

**Comment by boblauer** [comment]
I believe this is what you want: https://www.npmjs.com/package/babel-plugin-add-module-exports

**Comment by cayasso** [comment]
cacheman-redis@1.1.2 is out with the fix. The problem was that babel 6.x no longer support `module.export` according to this http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default so by installing this plugin `babel-plugin-add-module-exports` everything went back to normal :)

**Comment by cayasso** [comment]
Exactly @boblauer 
@mdurling thanks for reporting the issue, I am closing this!!!
