### ISSUE TITLE
redis clear error, Not anyting to be delete

### ISSUE THREAD

**Issue by cjy37** [cayasso/cacheman-redis#11]
sails.cacheman = require('sailsjs-cacheman');
...
var cacheKey = "project_list1";
var cache = sails.cacheman.sailsCacheman('mosproject1');
cache.clear(function (err) {
      if (err) throw err;
      // cache is now clear
      console.log('clear cache');
    });

//Not anyting to be del
1. check code : cacheman-redis/index.js line:147>>
store.client.keys(key + '*', function keys(err, data) { // data len = 0
2. modify to : store.client.keys('cache'+key + '*', function keys(err, data) { // data len > 0

check redis client, data not delete,
3. modify cacheman-redis/index.js line:147>>:  to
store.client.del(key.substr(5), function del(err, data) {

ok, bug fixed!

cacheman-redis v0.2.0

**Comment by cayasso** [comment]
yea latest version is `1.1.2`. 
closing...
