### ISSUE TITLE
The key prefix is duplicated

### ISSUE THREAD

**Issue by Sweetchuck** [cayasso/cacheman-redis#12]
# The problem

The main `cacheman` library adds the _prefix_ to the _key_ in the `get()`, `set()` and `del()` methods before it calls the corresponding methods of the cache backend.

The wrapper adds the prefix to the key by the `this.key(key)`
cacheman v2.1.0 [cacheman.set()](https://github.com/cayasso/cacheman/blob/9f135b94fe8ca445c4a437409c044b1810222cd2/lib/index.js#L280)

The backend also adds the prefix.
cacheman-redis v1.1.2 [RedisStore.get()](https://github.com/cayasso/cacheman-redis/blob/5d93d9b09a1028feae89d7400338a52154b7fb42/lib/index.js#L92)

# How to reproduce

```javascript
var options: {
  engine: 'redis',
  prefix: 'my-prefix',
  host: '127.0.0.1',
  port: 6379,
  database: 1
};
var Cacheman = require('cacheman');
var cache = new Cacheman('my_bin', options);
cache.set('my-key', 'my-data'); 
```

```
$ redis-cli -n 1
KEYS *
```
The result will be something like this:
`my-prefix:my-prefix:my_bin:my-key`

Excepted result is:
`my-prefix:my_bin:my-key`

**Comment by cayasso** [comment]
@Sweetchuck this is now fixed in the latest version cacheman@2.2.1 by this commit https://github.com/cayasso/cacheman/commit/06a361745480fa5f749de41b62d5a92d8b0b109d
