### ISSUE TITLE
del() is causing production outages because it is O(N)

### ISSUE THREAD

**Issue by tjulien** [cayasso/cacheman-redis#18]
Summary:

- Thank you for making cacheman, it is a great library that our application relies heavily on.
- `index.del()` [calls the redis `KEYS` function](https://github.com/cayasso/cacheman-redis/blob/master/lib/index.js#L126), which is `O(N)` and documented as [not to be used in production](https://redis.io/commands/keys).
- This is causing latency spikes that last 10s of seconds or minutes in our application
- Recommend consider removing or making optional the `KEYS` call in `index.del()`.
- I'm happy to submit a PR with a fix if this issue is accepted and an approach to solving this is agreed upon by the maintainers.

Details:
We are seeing large latency spikes in our application at times when updating records in mongo and purging those records from redis.  For example:

<img width="645" alt="redis latency spike" src="https://user-images.githubusercontent.com/155192/39385101-25ac0616-4a3d-11e8-9d6b-763a5bc82fe7.png">

Triaging this via `SLOWLOG` in redis revealed `KEYS` commands that line up with these latency spikes and take take ~1000ms per keys operation. In each entry below, 3) is latency in microseconds as explained by [SLOWLOG docs](https://redis.io/commands/slowlog).

```
127.0.0.1:6379> SLOWLOG GET 10
 1) 1) (integer) 791
    2) (integer) 1524855930
    3) (integer) 971006
    4) 1) "keys"
       2) "cacheman:cachegoose-cache:<KEY_SCRUBBED>"
 2) 1) (integer) 790
    2) (integer) 1524855928
    3) (integer) 974308
    4) 1) "keys"
       2) "cacheman:cachegoose-cache:<KEY_SCRUBBED>"
 3) 1) (integer) 789
    2) (integer) 1524855927
    3) (integer) 975268
    4) 1) "keys"
       2) "cacheman:cachegoose-cache:<KEY_SCRUBBED>"
```

The redis `keys` [documentation](https://redis.io/commands/keys) recommends against using `keys` in production:

`Time complexity: O(N) with N being the number of keys in the database, under the assumption that the key names in the database and the given pattern have limited length.`
...
`Warning: consider KEYS as a command that should only be used in production environments with extreme care. It may ruin performance when it is executed against large databases. This command is intended for debugging and special operations, such as changing your keyspace layout. Don't use KEYS in your regular application code. If you're looking for a way to find keys in a subset of your keyspace, consider using SCAN or sets.`

I am happy to make a fix and submit a PR.

**Comment by tjulien** [comment]
I forgot to mention one thing.

Because redis is single threaded, slow queries like `KEYS` render the redis cluster as unavailable - all other requests block waiting for these commands to finish, hence the severity of the issue.

**Comment by killroyboy** [comment]
Is there any update to this? I see the pull request, but it hasn't been merged. My redis is getting hammered because of it and my provider is getting frustrated.

**Comment by cayasso** [comment]
Hi guys sorry for the delay on this, I been a sick and couldn't get to this on time, I will take care of it right now.

**Comment by cayasso** [comment]
2.0.0 is out with the fix for this issue, thanks for reporting!

**Comment by tjulien** [comment]
Thanks @cayasso !  Health comes first, totally get it.

**Comment by loris** [comment]
@cayasso @tjulien our usage of cacheman-redis relies on the fact that we can delete all entries matching a prefix (ie, `cache.del('foo:*')` removes all the keys prefixed by `foo:`). From my understanding of the PR, this is not possible anymore. Is this correct? Any workaround?

**Comment by cayasso** [comment]
@loris Not from `cache.del` but I can add this to `clear` as like in the beginning, so `clear` would support `cache.clear(fn)` and `cache.key(`key:*`, fn)` as optional.
What do you think?

**Comment by loris** [comment]
@cayasso you mean `cache.clear("key:*", fn)`? looks fine to me, but it will have the same O(N) drawback as the previous `cache.del("key:*", fn)` implementation?

**Comment by cayasso** [comment]
Well yes, but I am not sure if its the best to do, it looks like deleting keys with patterns does not have a standard and efficient way to be done in Redis, I saw this the other day https://github.com/NodeRedis/node_redis/issues/1314#issuecomment-370488211 which looks like an efficient way but the implementation is huge, so I am not sure if its really something that this small library should support. Thoughts?

**Comment by killroyboy** [comment]
I think the key is to have the option to use pattern matching. Either implement the pattern matching in `cache.clear` as suggested or create a separate method (eg `cache.delMany`). I think it makes sense within `cache.clear` as long as you allow backwards compatibility. Meaning detect if a function vs string is passed as the first arg.

This forces the implementer to determine whether they want to take the O(N) hit.
